local Config = {

	Markers = 30,
	StartFrequency = 100,
	EndFrequency = 1500,

	MusicList = {
		{
			MusicKey = "multo",
			SoundId = 1846088038,
			MusicName = "Multo",
			MusicArtist = "Cup Of Joe",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "pahina",
			SoundId = 1848354536,
			MusicName = "Pahina",
			MusicArtist = "Cup Of Joe",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "kantang_para_sayo",
			SoundId = 1846088038,
			MusicName = "Kantang Para Sayo",
			MusicArtist = "Arco",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "breeze_cafe",
			SoundId = 1848354536,
			MusicName = "Breeze Café",
			MusicArtist = "-",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "let_me_be_the_one",
			SoundId = 1846088038,
			MusicName = "Let me Be The One",
			MusicArtist = "Jimmy Bondoc",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "hindi_tayo_pwede",
			SoundId = 1848354536,
			MusicName = "Hindi Tayo Pwede",
			MusicArtist = "The Juans",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "mata_sa_mata",
			SoundId = 1846088038,
			MusicName = "Mata sa Mata",
			MusicArtist = "7th",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "dusk_til_dawn",
			SoundId = 1848354536,
			MusicName = "Dusk 'til Dawn",
			MusicArtist = "Glaiza De Castro",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "hindi_ako_mawawala",
			SoundId = 1846088038,
			MusicName = "Hindi Ako Mawawala",
			MusicArtist = "El Manu",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "kahel_na_langit",
			SoundId = 1848354536,
			MusicName = "Kahel Na Langit",
			MusicArtist = "Maki",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "palagi",
			SoundId = 1846088038,
			MusicName = "Palagi",
			MusicArtist = "TJ Monterde",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "burnout",
			SoundId = 1848354536,
			MusicName = "Burnout",
			MusicArtist = "-",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "tingin",
			SoundId = 1846088038,
			MusicName = "Tingin",
			MusicArtist = "Cup of Joe",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "sa_bawat_sandali",
			SoundId = 1848354536,
			MusicName = "Sa Bawat Sandali",
			MusicArtist = "Amiel Sol",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "unti_unti",
			SoundId = 1846088038,
			MusicName = "Unti-unti",
			MusicArtist = "UDD",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "tapusin_na_natin_to",
			SoundId = 1848354536,
			MusicName = "Tapusin Na Natin To",
			MusicArtist = "Juan Karlos",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "kisame",
			SoundId = 1846088038,
			MusicName = "Kisame",
			MusicArtist = "rhodessa",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "sandali_na_lang",
			SoundId = 1848354536,
			MusicName = "Sandali Na Lang",
			MusicArtist = "Hale",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "umaasa",
			SoundId = 1846088038,
			MusicName = "Umaasa",
			MusicArtist = "CALEIN",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "hintai",
			SoundId = 1848354536,
			MusicName = "Hintai",
			MusicArtist = "-",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "pahintulot",
			SoundId = 1846088038,
			MusicName = "Pahintulot",
			MusicArtist = "Shirebound",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "di_na_babalik",
			SoundId = 1848354536,
			MusicName = "Di Na Babalik",
			MusicArtist = "This Band",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "masiram",
			SoundId = 1846088038,
			MusicName = "Masiram",
			MusicArtist = "Just Hush",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "burgis",
			SoundId = 1848354536,
			MusicName = "Burgis",
			MusicArtist = "Hev Abi",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "supafly",
			SoundId = 1846088038,
			MusicName = "Supafly",
			MusicArtist = "Answer The G",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "alam_mo_ba_girl",
			SoundId = 1848354536,
			MusicName = "Alam Mo Ba Girl",
			MusicArtist = "Hev Abi",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "pa_umaga",
			SoundId = 1846088038,
			MusicName = "Pa Umaga",
			MusicArtist = "Al James",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "tagay",
			SoundId = 1848354536,
			MusicName = "Tagay",
			MusicArtist = "J King",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "gusto_with_ya",
			SoundId = 1846088038,
			MusicName = "Gusto With Ya",
			MusicArtist = "DENY",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			MusicKey = "pero_atik_ra",
			SoundId = 1848354536,
			MusicName = "Pero Atik Ra",
			MusicArtist = "Jacky Chang",
			AlbumIcon = "rbxassetid://85945661957976",
		},
	},
}

return Config
