local Config = {

	Markers = 30,
	StartFrequency = 100,
	EndFrequency = 1500,

	MusicList = {
		{
			SoundId = 120119493259513,
			MusicName = "Multo",
			MusicArtist = "Cup Of Joe",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 125002803163167,
			MusicName = "Pahina",
			MusicArtist = "Cup Of Joe",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 103152537652330,
			MusicName = "Kantang Para Sayo",
			MusicArtist = "Arco",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 133359649173018,
			MusicName = "Breeze Café",
			MusicArtist = "-",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 110905674073393,
			MusicName = "Let me Be The One",
			MusicArtist = "Jimmy Bondoc",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 88969530862661,
			MusicName = "Hindi Tayo Pwede",
			MusicArtist = "The Juans",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 79861783316209,
			MusicName = "Mata sa Mata",
			MusicArtist = "7th",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 119700935596421,
			MusicName = "Dusk 'til Dawn",
			MusicArtist = "Glaiza De Castro",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 91882493348032,
			MusicName = "Hindi Ako Mawawala",
			MusicArtist = "El Manu",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 119836664075528,
			MusicName = "Kahel Na Langit",
			MusicArtist = "Maki",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 108434203980995,
			MusicName = "Palagi",
			MusicArtist = "TJ Monterde",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 115771102959956,
			MusicName = "Burnout",
			MusicArtist = ":<",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 117611424166121,
			MusicName = "Tingin",
			MusicArtist = "Cup of Joe",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 88398808795704,
			MusicName = "Sa Bawat Sandali",
			MusicArtist = "Amiel Sol",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 84914972774650,
			MusicName = "Unti-unti",
			MusicArtist = "UDD",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 126613503607893,
			MusicName = "Tapusin Na Natin To",
			MusicArtist = "Juan Karlos",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 109980096407694,
			MusicName = "Kisame",
			MusicArtist = "rhodessa",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 125573798906377,
			MusicName = "Sandali Na Lang",
			MusicArtist = "Hale",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 133925046853167,
			MusicName = "Umaasa",
			MusicArtist = "CALEIN",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 115484449607407,
			MusicName = "Hintai",
			MusicArtist = "-",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 125829703196270,
			MusicName = "Pahintulot",
			MusicArtist = "Shirebound",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 100994313196426,
			MusicName = "Di Na Babalik",
			MusicArtist = "This Band",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 126826302973007,
			MusicName = "Masiram",
			MusicArtist = "Just Hush",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 114211812512071,
			MusicName = "Burgis",
			MusicArtist = "Hev Abi",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 76095423286185,
			MusicName = "Supafly",
			MusicArtist = "Answer The G",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 130747392139198,
			MusicName = "Alam Mo Ba Girl",
			MusicArtist = "Hev Abi",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 129145099024653,
			MusicName = "Pa Umaga",
			MusicArtist = "Al James",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 118641397785171,
			MusicName = "Tagay",
			MusicArtist = "J King",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 130606620833917,
			MusicName = "Gusto With Ya",
			MusicArtist = "DENY",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 115961454016770,
			MusicName = "Pero Atik Ra",
			MusicArtist = "Jacky Chang",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 130393004369850,
			MusicName = "Dating Tayo.",
			MusicArtist = "©",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 75988266614461,
			MusicName = "Paralumbay.",
			MusicArtist = "©",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 93571222878830,
			MusicName = "Isip.",
			MusicArtist = "©",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 90139320588085,
			MusicName = "Sino.",
			MusicArtist = "©",
			AlbumIcon = "rbxassetid://85945661957976",
		},

		{
			SoundId = 87915025957041,
			MusicName = "Halik Sa Hangin.",
			MusicArtist = "©",
			AlbumIcon = "rbxassetid://85945661957976",
		},
	},
}

return Config
